### ISSUE TITLE
Why I can't find the code of PeCo?

### ISSUE THREAD

**Issue by pqh-zjut** [xyzforever/BEVT#4]

**Comment by cddlyf** [comment]
@QiE105 PeCo model is still under the company policy check, and will be out after it is done.

**Comment by pqh-zjut** [comment]
thank you sir, I'm looking forward for it

> under

**Comment by xiao2mo** [comment]
update for peco code.
thanks in advance.

**Comment by xiao2mo** [comment]
+1 for peco

**Comment by xiao2mo** [comment]
+1 for peco

**Comment by xiao2mo** [comment]
+1 for peco

**Comment by xiao2mo** [comment]
+1 for peco??????

**Comment by xiao2mo** [comment]
So, once the paper is accepted, u guys seems no burden at all.
